/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.fodizi.main;

import cn.fodizi.model.DelPath;
import cn.fodizi.myclass.JiShuLabel;
import cn.fodizi.myclass.Player;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;

/**
 *
 * @author wp
 */
public class JiSuFrame extends javax.swing.JFrame {
    
    /**
     * 提供集数面板 Creates new form JiSuFrame
     *
     * @param s
     */
    private static RootWindow rt = RootWindow.getRootWindow();
    private static String paString = System.getProperty("user.dir") + File.separator + "img" + File.separator + "1.jpg";
    
    public JiSuFrame(String s) {
        super(s);
        initComponents();
        setAlwaysOnTop(true);
        setLocation(rt.getX() +150,rt.getY()+100);
        
    }
    
    public void myShow() {
        //this.setResizable(false);
        Toolkit tool = this.getToolkit(); //得到一个Toolkit对象
        Image image = tool.createImage(paString);
        this.setIconImage(image);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addLable(String title, String url) {
        JiShuLabel jiShuLabel = new JiShuLabel(title, url);
        final JiSuFrame jsf = this;
        jiShuLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JiShuLabel jjj = (JiShuLabel) e.getSource();
                jsf.setAlwaysOnTop(false);
                Player.play(DelPath.getUrlMap().get(jjj.getUrl()));
            }
        });
        this.add(jiShuLabel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
