/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.fodizi.main;

import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author wp
 */
public class KindVideoFrame extends javax.swing.JFrame {

    private static ArrayList<JPanel> jPanels = new ArrayList<JPanel>();
    private int index = 0;
    private static RootWindow rt = RootWindow.getRootWindow();
    private static String paString = System.getProperty("user.dir") + File.separator + "img" + File.separator + "1.jpg";

    /**
     * Creates new form KindVideoFrame
     */
    private KindVideoFrame() {
        initComponents();
    }

    public KindVideoFrame(String title) {
        super(title);
        initComponents();
        setLocation(rt.getX(), rt.getY() - 50);
        jPanels.clear();
        jPanels.add(jPanel2);
        jPanels.add(jPanel3);
        jPanels.add(jPanel4);
        for (JPanel jPanel : jPanels) {
            jPanel.removeAll();
        }

    }

    public void myShow() {
        Toolkit tool = this.getToolkit(); //得到一个Toolkit对象
        Image image = tool.createImage(paString);
        this.setIconImage(image);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(jPanel4);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        setSize(new java.awt.Dimension(900, 900));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private static javax.swing.JPanel jPanel4;
    private static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component add(Component comp) {
        //System.out.println("======================");
        //System.out.println(this.getTitle());
        jPanels.get(index % 3).add(comp);
        index++;
        return this;
    }

}
